### ISSUE TITLE
Which is the most up to date release of matterbar?

### ISSUE THREAD

**Issue by idrysdale** [danieliu/matterbar#1]
Hello, firstly thanks for working on this plug-in, I'm looking forward to getting it installed. 😄

I see there are two forks of matterbar, one here, and one by [Affirm](https://github.com/Affirm)

I'm a bit confused, as your description of the project says 'MOVED TO https://github.com/Affirm/matterbar', however it appears you've since released a more up to date version of the plug-in.

* [Affirm release 0.2.0](https://github.com/Affirm/matterbar/releases/tag/v0.2.0) (19 Nov 2018)
* [danieliu release 1.2.0](https://github.com/danieliu/matterbar/releases/tag/v1.2.0) (11 Dec 2019)

To add to the confusion, the [Mattermost integration docs](https://integrations.mattermost.com/rollbar-plugin/) link to that old Affirm release, too.

Please can you help clear things up? Which is the latest, most stable release?

**Comment by fawkesley** [comment]
@danieliu @mahendra I'd like to know too - if you could clarify that would be great, thanks!

**Comment by danieliu** [comment]
@idrysdale @paulfurley there is a [pull request](https://github.com/Affirm/matterbar/pull/1) to merge in the latest from here into the "official" one under Affirm.

You may use either, although, of course, the most updated, recent version *should* be more stable. Keep in mind that 0.2.0 has been running under a "production" environment while 1.2.0 has been officially on been running under testing and dev environments.

Feel free to open an issue if you run into any problems.
